language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
branches:
  only:
    - release/beta
install:
  - npm install
script:
  - npm test
before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm run build:prod
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local-dir: dist
  region: eu-central-1
  on:
    branch: release/beta
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'release/beta'
